const car=['Honda','Bmw','Tesla','Tata','Thar']
console.log(car)
car.push("Benz")
console.log(car)
car.unshift("Audi")
console.log(car)
car.pop()
console.log(car)
car.shift()
console.log(car)
console.log(car.length)
console.log(car[1])
console.log(car[3])
console.log(car.join('-'))